[package]
name = "leptos-use"
version = "0.7.0"
edition = "2021"
authors = ["Marc-Stefan Cassola"]
categories = ["gui", "web-programming"]
description = "Collection of essential Leptos utilities inspired by SolidJS USE / VueUse"
exclude = ["examples/", "tests/"]
keywords = ["leptos", "utilities"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/Synphonyte/leptos-use"
homepage = "https://leptos-use.rs"

[dependencies]
leptos = "0.5"
wasm-bindgen = "0.2"
js-sys = "0.3"
default-struct-builder = "0.5"
num = { version = "0.4", optional = true }
serde = { version = "1", optional = true }
serde_json = { version = "1", optional = true }
paste = "1"
lazy_static = "1"
cfg-if = "1"
wasm-bindgen-futures = "0.4"
async-trait = "0.1"
rmp-serde = { version = "1.1", optional = true }
thiserror = "1"

[dependencies.web-sys]
version = "0.3"
features = [
    "AddEventListenerOptions",
    "BinaryType",
    "Coordinates",
    "CloseEvent",
    "CssStyleDeclaration",
    "CustomEvent",
    "CustomEventInit",
    "DomRect",
    "DomRectReadOnly",
    "DataTransfer",
    "DragEvent",
    "Element",
    "EventListener",
    "EventListenerOptions",
    "EventTarget",
    "File",
    "FileList",
    "Geolocation",
    "HtmlElement",
    "HtmlLinkElement",
    "HtmlStyleElement",
    "IntersectionObserver",
    "IntersectionObserverInit",
    "IntersectionObserverEntry",
    "MediaQueryList",
    "MouseEvent",
    "MutationObserver",
    "MutationObserverInit",
    "MutationRecord",
    "Navigator",
    "NodeList",
    "PointerEvent",
    "Position",
    "PositionError",
    "PositionOptions",
    "ReadableStream",
    "ReadableStreamDefaultReader",
    "ReadableStreamGetReaderOptions",
    "ReadableStreamReaderMode",
    "ResizeObserver",
    "ResizeObserverBoxOptions",
    "ResizeObserverEntry",
    "ResizeObserverOptions",
    "ResizeObserverSize",
    "ScrollBehavior",
    "ScrollToOptions",
    "Storage",
    "Touch",
    "TouchEvent",
    "TouchList",
    "VisibilityState",
    "WebSocket",
    "WebTransport",
    "WebTransportOptions",
    "WebTransportDatagramDuplexStream",
    "WebTransportBidirectionalStream",
    "Window",
    "WebTransportReceiveStream",
    "WebTransportSendStream",
    "WritableStream",
    "WritableStreamDefaultWriter",
]

[features]
docs = []
math = ["num"]
storage = ["dep:serde", "dep:serde_json", "web-sys/StorageEvent"]
ssr = []
msgpack = ["dep:rmp-serde", "dep:serde"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg=web_sys_unstable_apis"]
rustc-args = ["--cfg=web_sys_unstable_apis"]

